import { EntidadCompradora, EntidadProveedora, Eventos, Parametros } from './index';

export class ConsultaDocumento {

    public chCodigointerno: string;
    public chEstadocomprobantepago: string;
    public chEstadocomprobantepagocomp: string;
    public chFlagorigencomprobantepago: string;
    public chFlagorigencreacion: string;
    public chFlagplazopago: string;
    public chFlagregistroeliminado: string;
    public chIdtipocomprobante: string;
    public chMonedacomprobantepago: string;
    public chOpregfac: string;
    public chTiempoplazo: any;
    public chTipoemision: string;
    public deDctomonto: string;
    public deDctomontoultimo: any;
    public deDescuento: any;
    public deImportereferencial: any;
    public deImpuesto1: any;
    public deImpuesto2: any;
    public deImpuesto3: any;
    public deImpuestogvr: any;
    public dePagomontopagado: any;
    public dePagomontopagadoultimo: any;
    public dePorcentajeimpuesto: any;
    public deSubtotalcomprobantepago: any;
    public deTotalcomprobantepago: any;
    public entidadcompradora: EntidadCompradora[] = [];
    public entidadproveedora: EntidadProveedora[] = [];
    public eventos: Eventos[] = [];
    public inDeguiapublicada: any;
    public inDetraccion: any;
    public inIdarchivoCdr: any;
    public inIdarchivoPdf: any;
    public inIdarchivoXml: any;
    public inIdbienservicio: any;
    public inIdcomprobantepago: string;
    public inIdguia: any;
    public inIdindicadorimpuesto: any;
    public inIdoc: any;
    public inIdorganizacioncompradora: any;
    public inIdorganizacioncreacion: any;
    public inIdorganizacionmodificacion: any;
    public inIdorganizacionproveedora: string;
    public inIdtransportista: any;
    public inIdusuariocomprador: any;
    public inIdusuariocreacion: string;
    public inIdusuariomodificacion: string;
    public inIdusuarioproveedor: any;
    public inVersion: any;
    public parametros: Parametros[] = [];
    public tsFechacambioestado: string;
    public tsFechacreacion: any;
    public tsFechadocumentoret: string;
    public tsFechaemision: string;
    public tsFechaenvio: string;
    public tsFechahoracreacion: any;
    public tsFechapagocomprobantepago: any;
    public tsFechaprogpagocomprobantepag: any;
    public tsFecharecepcioncomprobantepa: any;
    public tsFecharegistro: any;
    public tsFechavencimiento: any;
    public tsParamFechabaja: any;
    public vcArchivocdrUbicacion: string;
    public vcArchivopdfUbicacion: string;
    public vcArchivoxmlUbicacion: string;
    public vcCoderror: string;
    public vcCodigobienservicio: string;
    public vcCodigoerp: string;
    public vcCodigoerpproveedor: string;
    public vcCodigosociedad: string;
    public vcCondicionpago: string;
    public vcCorrelativo: string;
    public vcDctomoneda: string;
    public vcDctonrodocumento: string;
    public vcDctotipodocumento: string;
    public vcDescerror: string;
    public vcDescripcionbienservicio: string;
    public vcDescripcioncondicionpago: string;
    public vcDocumentopago: string;
    public vcDocumentosap: string;
    public vcFirma: string;
    public vcFormapago: string;
    public vcIdcondicionpago: string;
    public vcIdregistroestadocomp: string;
    public vcIdregistroestadoprov: string;
    public vcIdregistromoneda: string;
    public vcIdregistrotipocomprobante: string;
    public vcIdtablaestado: string;
    public vcIdtablamoneda: string;
    public vcIdtablatipocomprobante: string;
    public vcIndicadorimpuesto: string;
    public vcLlaveerp: string;
    public vcLogo: string;
    public vcMontocomprobantepago: string;
    public vcNrocheque: string;
    public vcNumguia: string;
    public vcNumoc: string;
    public vcObscomprobantepago: string;
    public vcObspagocomprobantepago: string;
    public vcOrgcompradoraCorreo: string;
    public vcOrgcompradoraDenominacio: string;
    public vcOrgcompradoraDirfiscal: string;
    public vcOrgcompradoraDocumento: string;
    public vcOrgcompradoraNomcomercial: string;
    public vcOrgproveedoraCorreo: string;: string;
    public vcOrgproveedoraDenominacion: string;
    public vcOrgproveedoraDirfiscal: string;
    public vcOrgproveedoraDocumento: string;
    public vcOrgproveedoraNomcomercial: string;
    public vcPagobanco: string;
    public vcPagomoneda: string;
    public vcPagonrodocumento: string;
    public vcPagotipodocumento: string;
    public vcParamTicket: string;
    public vcPorcentajedetraccion: string;
    public vcSerie: string;
    public vcTicketRetencion: string;
    public vcTipocomprobante: string;
    public vcTipofactura: string;
    public vcTransportistaDenominacion: string;
    public vcTransportistaDocumento: string;

    constructor(){}
}
