platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - 1002.OFE_DESKTOP\node_modules

install:
  - ps: Install-Product node 8 x64
#  - npm i --save electron
#  - npm i --save-dev electron-rebuild
#  - npm install sqlite3 --save
#  - npm install --global --production windows-build-tools
#  - npm install --global node-gyp
#  - npm run rebuild
  - cd 1002.OFE_DESKTOP 
  - npm install
  - npm i html-webpack-plugin --save-dev
  - cd ../"1002.OFE_DESKTOP ADMINISTRADOR"
  - npm install
  - npm i html-webpack-plugin --save-dev
  - cd ..




build_script:
  - cd 1002.OFE_DESKTOP
  - npm run build_dev  
  - cd ..
  - xcopy /y 1002.OFE_DESKTOP\dist\* 1002.OFE-PROD\PROD_ANGULAR\dist /s /i
  - xcopy /y /i /R 1002.OFE-PROD\PROD_ANGULAR\index.html 1002.OFE-PROD\PROD_ANGULAR\dist\index.html 
  - npm install
  - xcopy /y "dist\Sistema_de_Facturacion_Electronica_Offline Setup 20.6.1.exe" "offline.exe*"
  - xcopy /y "dist\Sistema_de_Facturacion_Electronica_Offline Setup 20.6.1.exe" "dist\Sistema_de_Facturacion_Electronica_Offline"%APPVEYOR_BUILD_VERSION%".exe*"
  - del "dist\Sistema_de_Facturacion_Electronica_Offline Setup 20.6.1.exe"
  - cd "1002.OFE_DESKTOP ADMINISTRADOR"
  - npm run build_dev  
  - cd ..
  - xcopy /y "1002.OFE_DESKTOP ADMINISTRADOR"\dist\* 1002.OFE-PROD\PROD_ANGULAR\dist /s /i
  - xcopy /y /i /R 1002.OFE-PROD\PROD_ANGULAR\index.html 1002.OFE-PROD\PROD_ANGULAR\dist\index.html 
  - xcopy /y /i /R main-administrador.js main.js
  - npm install
  - xcopy /y "dist\Sistema_de_Facturacion_Electronica_Offline Setup 20.6.1.exe" "offlineAdministrador.exe*"
  - xcopy /y "dist\Sistema_de_Facturacion_Electronica_Offline Setup 20.6.1.exe" "dist\Sistema_de_Facturacion_Electronica_Offline_Administrador"%APPVEYOR_BUILD_VERSION%".exe*"
  - del "dist\Sistema_de_Facturacion_Electronica_Offline Setup 20.6.1.exe"

artifacts:
 - path: dist\Sistema*.exe
   name: version
 - path: offlin*.exe
   name: versionlast

deploy:
 - provider: FTP
   protocol: sftp
   host: $(ftphost)
   username: $(ftpusername)
   password: $(ftppassword)
   folder: $(APPVEYOR_REPO_BRANCH)
   artifact: version
 - provider: AzureBlob
   storage_account_name: saoce
   storage_access_key: $(azureblobkey)
   container: $(container)
   folder: offline
   artifact: versionlast
   unzip: false
   set_content_type: false

for:
-
 branches:
   only:
     - development
 environment:
   container: febiz

-
 branches:
   only:
     - qa
 environment:
   container: febiz-qa
-
 branches:
   only:
     - master
 environment:
   container: febiz-prd
test: off
