import {Producto} from './producto';

export class Detalle {
  inIdcomprobantepagodetalle: string;
  inIdcomprobantepago: string;
  inItipoPrecioventa: number;
  inCodigoPrecioventa: number;
  vcDescPrecioventa: string;
  inItipoCalculoisc: number;
  inCodigoCalculoisc: number;
  vcDescCalculoisc: string;
  inItipoAfectacionigv: number;
  inCodigoAfectacionigv: number;
  vcDescAfectacionigv: string;
  chAfectaIgv: number;
  inIdguia: string;
  vcSpotimpuesto: string;
  chNumeroseguimiento: string;
  chNumeroguia: string;
  vcDescripcionitem: string;
  vcPosicionprodxguia: string;
  vcNumeroparteitem: string;
  vcPosicionprodxoc: string;
  inIdproductoconsignado: number;
  dePreciounitarioitem: number;
  deCantidaddespachada: number;
  inIdmovimiento: string;
  vcCodigoguiaerp: string;
  vcEjercicioguia: string;
  vcTipoguia: string;
  tsFechaemisionguia: string;
  vcTipospot: string;
  dePorcentajeimpuesto: number;
  deMontoimpuesto: number;
  inIproducto: number;
  vcCodigoProducto: string;
  vcPosicion: number;
  dePreciototalitem: number;
  vcUnidadmedida: string;
  nuSubtotalIgv: number;
  nuSubtotalIsc: number;
  nuPesoBruto: number;
  nuPesoNeto: number;
  nuPesoTotal: number;
  nuDescuento: number;
  producto: Producto;
}
