import {DetalleNotaCredito} from './detalleNotaCredito';
import {EntidadNotaCredito} from './entidadNotaCredito';
import {DocumentoConceptoNotaCredito} from './documentoConceptoNotaCredito';
import {DocumentoParametroNotaCredito} from './documentoParametroNotaCredito';
import {DocumentoReferenciaNotaCredito} from './documentoReferenciaNotaCredito';
import {TablaMaestra} from '../../../general/models/documento/tablaMaestra';

export class NotaCredito {
  numeroComprobante: string;
  rucProveedor: string;
  rucComprador: string;
  idTablaTipoComprobante: string;
  idRegistroTipoComprobante: string;
  idTipoComprobante: string;
  razonSocialProveedor: string;
  razonSocialComprador: string;
  moneda: string;
  fechaEmision: number;
  observacionComprobante: string;
  tipoComprobante: string;
  montoPagado: string;
  igv: string;
  isc: string;
  otrosTributos: string;
  descuento: string;
  importeReferencial: string;
  subtotalComprobante: string;
  totalComprobante: string;
  tipoItem: string;
  idTablaMoneda: string;
  idRegistroMoneda: string;
  usuarioCreacion: string;
  usuarioModificacion: string;
  idSerie: string;
  motivoComprobante: string;
  detalleEbiz: DetalleNotaCredito[];
  documentoEntidad: EntidadNotaCredito[];
  documentoConcepto: DocumentoConceptoNotaCredito[];
  documentoParametro: DocumentoParametroNotaCredito[];
  documentoReferencia: DocumentoReferenciaNotaCredito[];
  auxMonedaTablaMaestra: TablaMaestra;

  constructor() {
    this.numeroComprobante = '';
    this.rucProveedor = '';
    this.rucComprador = '';
    this.idTablaTipoComprobante = '';
    this.idRegistroTipoComprobante = '';
    this.idTipoComprobante = '';
    this.razonSocialProveedor = '';
    this.razonSocialComprador = '';
    this.moneda = '';
    this.fechaEmision = 0;
    this.observacionComprobante = '';
    this.tipoComprobante = '';
    this.montoPagado = '';
    this.igv = '';
    this.isc = '';
    this.otrosTributos = '';
    this.descuento = '';
    this.importeReferencial = '';
    this.subtotalComprobante = '';
    this.totalComprobante = '';
    this.tipoItem = '';
    this.idTablaMoneda = '';
    this.idRegistroMoneda = '';
    this.usuarioCreacion = '';
    this.usuarioModificacion = '';
    this.idSerie = '';
    this.motivoComprobante = '';
    this.detalleEbiz = new Array<DetalleNotaCredito>() ;
    this.documentoEntidad = new Array<EntidadNotaCredito>();
    this.documentoConcepto = new Array<DocumentoConceptoNotaCredito>();
    this.documentoParametro = new Array<DocumentoParametroNotaCredito>();
    this.documentoReferencia = new Array<DocumentoReferenciaNotaCredito>();
    this.auxMonedaTablaMaestra = new TablaMaestra();
  }
}
