import { Injectable } from '@angular/core';

@Injectable()
export class TiposService {
    public TIPO_PRODUCTO_BIEN: number = 3;
    public TIPO_PRODUCTO_SERVICIO: number = 4;

    public CONSULTAS_BUSQUEDA_BOLETAS: number = 10;
    public CONSULTAS_BUSQUEDA_FACTURAS: number = 9;
    public CONSULTAS_RESUMEN_BOLETAS: number = 8;
    public CONSULTAS_GUIA_REMISION: number = 7;
    public CONSULTAS_RETENCION: number = 6;
    public CONSULTAS_PERCEPCION: number = 5;
    public CONSULTAS_NOTA_DEBITO: number = 4;
    public CONSULTAS_BOLETA: number = 3;
    public CONSULTAS_FACTURA: number = 2;

    public TIPO_DOCUMENTO_FACTURA: string = '01';
    public TIPO_DOCUMENTO_FACTURA_NOMBRE: string = 'Factura';
    public TIPO_DOCUMENTO_BOLETA: string = '03';
    public TIPO_DOCUMENTO_BOLETA_NOMBRE: string = 'Boleta de Venta';
    public TIPO_DOCUMENTO_NOTA_CREDITO: string = '07';
    public TIPO_DOCUMENTO_NOTA_CREDITO_NOMBRE: string = 'Nota de Crédito';
    public TIPO_DOCUMENTO_NOTA_DEBITO: string = '08';
    public TIPO_DOCUMENTO_NOTA_DEBITO_NOMBRE: string = 'Nota de Débito';
    public TIPO_DOCUMENTO_PERCEPCION: string = '40';
    public TIPO_DOCUMENTO_PERCEPCION_NOMBRE: string = 'Comprobante de Percepción';
    public TIPO_DOCUMENTO_RETENCION: string = '20';
    public TIPO_DOCUMENTO_RETENCION_NOMBRE: string = 'Retención';
    public TIPO_DOCUMENTO_GUIA_REMISION_REMITENTE: string = '09';
    public TIPO_DOCUMENTO_GUIA_REMISION_REMITENTE_NOMBRE: string = 'Guia Remisión Remitente';
    public TIPO_DOCUMENTO_GUIA_REMISION_TRANSPORTISTA: string = '31';
    public TIPO_DOCUMENTO_GUIA_REMISION_TRANSPORTISTA_NOMBRE: string = 'Guia Remisión Transportista';
    public TIPO_DOCUMENTO_FACTURA_ANTICIPO: string = '0000010';
    public TIPO_DOCUMENTO_FACTURA_ANTICIPO_NOMBRE: string = 'Factura de Anticipo';
    public TIPO_DOCUMENTO_BOLETA_ANTICIPO: string = '2000';
    public TIPO_DOCUMENTO_BOLETA_ANTICIPO_NOMBRE: string = 'Boleta de Anticipo';
    public TIPO_DOCUMENTO_RESUMEN_BAJAS: string = 'RR';
    public TIPO_DOCUMENTO_RESUMEN_BAJAS_NOMBRE: string = 'Resumen de Bajas';
    public TIPO_DOCUMENTO_RESUMEN_BOLETAS: string = 'RC';
    public TIPO_DOCUMENTO_RESUMEN_BOLETAS_NOMBRE: string = 'Resumen de Boletas';
    public TIPO_DOCUMENTO_COMUNICACION_BAJA_RETENCIONES_PERCEPCIONES: string = 'RR';
    public TIPO_DOCUMENTO_COMUNICACION_BAJA_FACTURA_BOLETA_NOTAS: string = 'RA';

    public TIPO_CONSULTA_COMPROBANTE: number = 1;
    public TIPO_CONSULTA_PERCEPCION_RETENCION: number = 2;
    public TIPO_CONSULTA_GUIA_REMISION: number = 3;
    public TIPO_CONSULTA_RESUMEN_BOLETAS: number = 4;
    public TIPO_CONSULTA_RESUMEN_BAJAS: number = 5;
    public TIPO_CONSULTA_FACTURA_DOCUMENTO_RELACIONADO: number = 9;
    public TIPO_CONSULTA_BOLETA_DOCUMENTO_RELACIONADO: number = 10;

    public TIPO_MONEDA_SOL: string = '0000001';
    public TIPO_FORMATO_NUMERICO: number = 0;
    public TIPO_FORMATO_ALFANUMERICO: number = 1;

    public TIPO_ESTADO_PENDIENTE_DE_ENVIO = 1;
    public TIPO_ESTADO_BLOQUEADO = 2;
    public TIPO_ESTADO_AUTORIZADO = 3;
    public TIPO_ESTADO_AUTORIZADO_CON_OBSERVACIONES = 4;
    public TIPO_ESTADO_RECHAZADO = 5;
    public TIPO_ESTADO_DADO_DE_BAJA = 6;
    public TIPO_ESTADO_ERROR = 99;

    public TIPO_SERIE_ONLINE = 1;
    public TIPO_SERIE_OFFLINE = 0;

    public CABECERA_RETENCIONES = "retenciones";
    public PARAMETRO_TIPO_TRIBUTO = 1;
    public PARAMETRO_TIPO_NOTA_CREDITO_ELECTRONICA = 2;
    public PARAMETRO_TIPO_NOTA_DEBITO_ELECTRONICA = 3;
    public PARAMETRO_TIPO_VALOR_VENTA = 4;
    public PARAMETRO_DOCUMENTOS_RELACIONADOS_TRIBUTARIOS = 5;
    public PARAMETRO_ELEMENTOS_ADICIONALES_FACTURA_BOLETA = 6;
    public PARAMETRO_TIPO_PRECIO_VENTA_UNITARIO = 7;
    public PARAMETRO_TIPO_OPERACION = 8;
    public PARAMETRO_REGIMENES_PERCEPCION = 19;
    public PARAMETRO_TIPO_CLIENTES = '06';
    public PARAMETRO_TIPO_PARAMETROS = '05';


    public TIPO_NOTA_CREDITO_ANULACION_DE_OPERACION = '01';
    public TIPO_NOTA_CREDITO_ANULACION_POR_ERROR_RUC = '02';
    public TIPO_NOTA_CREDITO_CORRECCION_DE_LA_DESCRIPCION = '03';
    public TIPO_NOTA_CREDITO_DESCUENTO_GLOBAL = '04';
    public TIPO_NOTA_CREDITO_DESCUENTO_POR_ITEM = '05';
    public TIPO_NOTA_CREDITO_DEVOLUCION_TOTAL = '06';
    public TIPO_NOTA_CREDITO_DEVOLUCION_POR_ITEM = '07';
    public TIPO_NOTA_CREDITO_BONIFICACION = '08';
    public TIPO_NOTA_CREDITO_DISMINUCION_EN_EL_VALOR = '09';


    public TIPO_NOTA_DEBITO_INTERES_POR_MORA = '01';
    public TIPO_NOTA_DEBITO_AUMENTO_EN_EL_VALOR = '02';
    public TIPO_NOTA_DEBITO_PENALIDADES_OTROS_CONCEPTOS = '03';

    public ID_TABLA_TIPO_COMPROBANTE = '10007';
    public ID_TABLA_TIPO_MONEDA = '10005';

    public CODIGO_TIPO_ISC_NO_TIENE = '00';
    public ID_ISC_ID_TIPO_NO_TIENE = '1';
    public DESCRIPCION_TIPO_ISC_NO_TIENE = 'No tiene';

    public TIPO_PRECIO_PRECIO_UNITARIO_ID = '01';
    public TIPO_PRECIO_PRECIO_UNITARIO_CODIGO = '01';
    public TIPO_PRECIO_PRECIO_UNITARIO_DESCRIPCION = 'Precio Unitario (Incluye el IGV)';
    public TIPO_PRECIO_VALOR_REFERENCIAL_UNITARIO_ID = '02';
    public TIPO_PRECIO_VALOR_REFERENCIAL_UNITARIO_CODIGO = '02';
    public TIPO_PRECIO_VALOR_REFERENCIAL_UNITARIO_DESCRIPCION = 'Valor Referencial Unitario en operaciones unitarias';

    public PREFIJO_PAIS_PERU = 'PE';
    public TIPO_ENTIDAD_EMISOR = '1';
    public TIPO_ENTIDAD_RECEPTOR = '2';
    public DESCRIPCION_TIPO_ENTIDAD_EMISOR = 'Emisor';
    public DESCRIPCION_TIPO_ENTIDAD_RECEPTOR = 'Receptor';

    public NOTIFICACION_DOCUMENTO_ENTIDAD = 'S';

    public CONCEPTO_OPERACION_GRAVADA_CODIGO = '1001';
    public CONCEPTO_OPERACION_INAFECTAS_CODIGO = '1002';
    public CONCEPTO_OPERACION_EXONERADO_CODIGO = '1003';
    public CONCEPTO_OPERACION_GRATUITA_CODIGO = '1004';
    public CONCEPTO_OPERACION_SUB_TOTAL_VENTA_CODIGO = '1005';
    public CONCEPTO_OPERACION_PERCEPCIONES_CODIGO = '2001';
    public CONCEPTO_OPERACION_RETENCIONES_CODIGO = '2002';
    public CONCEPTO_OPERACION_DETRACCIONES_CODIGO = '2003';
    public CONCEPTO_OPERACION_BONIFICACIONES_CODIGO = '2004';
    public CONCEPTO_OPERACION_TOTAL_DESCUENTOS_CODIGO = '2005';
    public CONCEPTO_OPERACION_FONDO_INCLUSION_SOCIAL_ENERGETICO_CODIGO = '3001';
    public CONCEPTO_OPERACION_OTROS_CARGOS_CODIGO = '9999';

    //  Factura Anticipo
    public FACTURA_ANTICIPO_IDENTIFICADOR_ITEM = -1;
    public FACTURA_ANTICIPO_VALOR_CODIGO_ITEM = '-';
    public FACTURA_ANTICIPO_ID_TIPO_IGV = '1';
    public FACTURA_ANTICIPO_CODIGO_TIPO_IGV = '10';
    public FACTURA_ANTICIPO_DESCRIPCION_TIPO_IGV = 'Gravado - Operación Onerosa';
    public FACTURA_ANTICIPO_ID_PARAMETRO = '5';
    public FACTURA_ANTICIPO_DESCRIPCION_PARAMETRO = 'Anticipo';
    public FACTURA_ANTICIPO_CODIGO_SUNAT = '02';
    public FACTURA_ANTICIPO_ID_DOMINIO = 26;
    public FACTURA_ANTICIPO_TIPO_PARAMETRO = 3;
    public FACTURA_ANTICIPO_TIPO_PARAMETRO_VALOR = 'Anticipos';

    //  Boletas Anticipo
    public BOLETA_ANTICIPO_IDENTIFICADOR_ITEM = -1;
    public BOLETA_ANTICIPO_VALOR_CODIGO_ITEM = '-';
    public BOLETA_ANTICIPO_ID_TIPO_IGV = '1';
    public BOLETA_ANTICIPO_CODIGO_TIPO_IGV = '10';
    public BOLETA_ANTICIPO_DESCRIPCION_TIPO_IGV = 'Gravado - Operación Onerosa';
    public BOLETA_ANTICIPO_ID_PARAMETRO = '5';
    public BOLETA_ANTICIPO_DESCRIPCION_PARAMETRO = 'Anticipo';
    public BOLETA_ANTICIPO_CODIGO_SUNAT = '03';
    public BOLETA_ANTICIPO_ID_DOMINIO = 26;
    public BOLETA_ANTICIPO_TIPO_PARAMETRO = 3;
    public BOLETA_ANTICIPO_TIPO_PARAMETRO_VALOR = 'Anticipos';

    public TIPO_RETENCION_MASIVA_CODIGO = '20';
    public TIPO_PRODUCTO_MASIVA_CODIGO = '0';

    public TIPO_MONEDA_PEN_ISO = 'PEN';
    public TIPO_MONEDA_USD_ISO = 'USD';
    public TIPO_MONEDA_EUR_ISO = 'EUR';
    public TIPO_MONEDA_PEN_DESCRIPCION = 'SOLES';
    public TIPO_MONEDA_USD_DESCRIPCION = 'DOLARES';
    public TIPO_MONEDA_EUR_DESCRIPCION = 'EUROS';

    public TIPO_PERCEPCION_VENTA_INTERNA_ID = 91;
    public TIPO_PERCEPCION_VENTA_INTERNA_TASA = 2;
    public TIPO_PERCEPCION_A_LA_ADQUISICION_DE_COMBUSTIBLE_TASA = 1;
    public TIPO_PERCEPCION_A_LA_ADQUISICION_DE_COMBUSTIBLE_ID = 92;
    public TIPO_PERCEPCION_REALIZADA_AL_AGENTE_DE_PERCEPCION_CON_TASA_ESPECIAL_TASA = 0.5;
    public TIPO_PERCEPCION_REALIZADA_AL_AGENTE_DE_PERCEPCION_CON_TASA_ESPECIAL_ID = 93;

}
